GET http://localhost:3000/foods/ HTTP/1.1
Content-Type: application/json
###

GET http://localhost:3000/foods/3 HTTP/1.1
Content-Type: application/json
###

POST http://localhost:3000/foods HTTP/1.1 
Content-Type: application/json

{
    "food":"Some nasty school lunch",
    "taste":"Disgusting but it's gratis, and gratis is gott",
    "price":0
}

### 

PUT http://localhost:3000/foods/2 HTTP/1.1
Content-Type: application/json

{
    "food": "Soup",
    "taste": "Good",
    "price": 12
}
### 

DELETE http://localhost:3000/foods/5 HTTP/1.1
Content-Type: application/json
